orders:
  queue:
    host: ${QHOST:docker-pool.localdomain}
    port: ${QPORT:5672}
    passwd: ${QPASSWD:pass}
    user: ${QUSR:user}
    queue-name: ${QNAME:orderqueue}
  services:
    address-host: ${ADDR_HOST:http://localhost:9001/address}
    cc-host: ${CC_HOST:http://localhost:9002/creditcard}
spring:
  data:
    mongodb:
      database: ${DB_NAME:OrderDB}
      host: ${DB_HOST:docker-pool.localdomain}
      port: ${DB_PORT:27020}
      username: ${DB_USR:rouslan}
      password: ${DB_PASSWD:50m9FiD3}
